# -*- coding: utf-8 -*-
"""EA_Final_Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pv_5pr79Mn76JtE6kNwuu9ChKJWrEgfI
"""

try:
  import streamlit as st
except ModuleNotFoundError:
  import os
  os.system("pip install streamlit")
  import streamlit as st

import pandas as pd
import plotly.express as px

df = pd.read_csv('fema_small.csv')

st.title("Fema Dashboard")

st.sidebar.header("Display")
with st.sidebar:
  display = st.sidebar.selectbox("What would you like to see?",
   ["Fema Data", "Histogram", "Boxplot"])

  st.divider()
  st.markdown("Because of the large dataset it can take a moment for the content to load")
  
if display == "Fema Data":
  st.subheader("Data Preview")
  st.write(df.head())

  st.subheader("Summary Statistics")
  st.write(df.describe())
elif display == "Histogram":
  st.subheader("Histogram of Repair Amount")
  fig_hist = px.histogram(df, x='repairAmount', nbins = 30, title='Distribution of Repair Amounts')
  st.plotly_chart(fig_hist)
  st.markdown("*Evan's Insight:* The distribution of repair amounts in our data is heavily skewed to the left. This means that there are likely a few high repair amounts in our data that are raising the average above the median.")
elif display == "Boxplot":
  st.subheader("Boxplot: Repair Amount by TSA Eligibility")
  fig_box = px.box(df, x='tsaEligible', y='repairAmount', title='Repair Amounts by TSA Eligibility',
                   labels={"tsaEligible":"TSA Eligible (1=Yes, 0=No)","repairAmount":"Repair_Amount"})
  st.plotly_chart(fig_box)
  st.markdown("*Evan's Insight:* The sample that I randomly took from the larger dataset I used for my model appears to have a large amount of outliers according to this boxplot. The median in both eligible and non eligible seem to be really close which is interesting.")
