# -*- coding: utf-8 -*-
"""EA_Final_Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pv_5pr79Mn76JtE6kNwuu9ChKJWrEgfI
"""

try:
  import streamlit as st
except ModuleNotFoundError:
  import os
  os.system("pip install streamlit")
  import streamlit as st

import pandas as pd
import plotly.express as px

df = pd.read_csv('fema_small.csv')

st.title("Fema Dashboard")
st.subheader("Data Preview")
st.write(df.head())

st.subheader("Histogram of Repair Amount")
fig_hist = px.histogram(df, x='repairAmount', nbins = 30, title='Distribution of Repair Amounts')
st.plotly_chart(fig_hist)

st.subheader("Boxplot: Repair Amount by TSA Eligibility")
fig_box = px.box(df, x='tsaEligible', y='repairAmount', title='Repair Amounts by TSA Eligibility',
                 labels={"tsaEligible":"TSA Eligible (1=Yes, 0=No)","repairAmount":"Repair_Amount"})
st.plotly_chart(fig_box)
st.markdown("*Insight:* Something or other")
